{% set version = "4.7.0" %}

package:
  name: libpysal
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/libpysal/libpysal-{{ version }}.tar.gz
  sha256: a4730688e2c8134930ff4de42d7be58e360c03904b859fa374dfd70dca1f93bf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - pytest-runner
  run:
    - python >=3.7
    - appdirs
    - beautifulsoup4
    - jinja2
    - numpy >=1.3
    - packaging
    - pandas
    - requests
    - scipy >=0.11
    # needed but not declared.
    - shapely

test:
  imports:
    - libpysal
    - libpysal.cg
    - libpysal.cg.ops
    - libpysal.examples
    - libpysal.io
    - libpysal.io.geotable
    - libpysal.io.iohandlers
    - libpysal.io.tests
    - libpysal.io.util
    - libpysal.weights
  # pip check is not smart enough to know that an import name is not the package name :-(
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://pysal.org
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Core components of PySAL A library of spatial analysis functions

extra:
  recipe-maintainers:
    - ocefpaf
    - jGaboardi
    - martinfleis
